### ISSUE TITLE
Can you share your AFD-former Baidu Netdisk model weights?

### ISSUE THREAD

**Issue by 647-bei** [House-yuyu/AFD-former#3]

**Comment by House-yuyu** [comment]
Thank you for your interest in our work. We have uploaded the pre-training weights to Baidu Netdisk.

**Comment by 647-bei** [comment]
Sorry to bother you again, but can you share the original dataset? I'm trying to follow your method to split the data. The dataset I found is missing Outdoor, Bookarrival, Gtfily, and Shark


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "House-yuyu/AFD-former"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月18日(星期一) 晚上7:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [House-yuyu/AFD-former] Can you share your AFD-former Baidu Netdisk model weights? (Issue #3)





 
Thank you for your interest in our work. We have uploaded the pre-training weights to Baidu Netdisk.

**Comment by House-yuyu** [comment]
We have uploaded the above data and added detailed description to the readme of the dataset file.

**Comment by 647-bei** [comment]
thanks for sharing. Could you please provide the camera parameter files and corresponding texture/depth video files of Outdoor and Bookarrival?

**Comment by House-yuyu** [comment]
Hi @647-bei, apologies for my delayed response. 

As an SVQE task, the camera parameters were not required throughout the experiment, so they are not of interest to us. 
Currently I don't have the corresponding texture files for "Outdoor" and "Bookarrival" on my company's device, they are on my personal device. Please note that the corresponding depth video files are not available. I will upload them later!
